@echo off

:: Install Chocolatey first

choco install -y                       ^
google-chrome-x64                      ^
keepass.install                        ^
spotify                                ^
7zip.commandline                       ^
7zip.install                           ^
atom                                   ^
audacity                               ^
ctags                                  ^
curl                                   ^
cutepdf                                ^
dotpeek                                ^
f.lux                                  ^
fiddler4                               ^
filezilla                              ^
firefox                                ^
foxitreader                            ^
git.install                            ^
greenshot                              ^
grepwin                                ^
heroku-toolbelt                        ^
kdiff3                                 ^
lockhunter                             ^
nodejs.install                         ^
notepadplusplus                        ^
nuget.commandline                      ^
nugetpackageexplorer                   ^
paint.net                              ^
papercut                               ^
poshgit                                ^
procexp                                ^
putty                                  ^
python2                                ^
ruby1.9                                ^
ruby.devkit                            ^
screenhero                             ^
screentogif                            ^
skype                                  ^
sysinternals                           ^
vlc                                    ^
wcat                                   ^
windirstat                             ^
winmerge                               ^
winscp                                 ^
wireshark                              ^
mssqlserver2014express                 ^
mssqlservermanagementstudio2014express ^
